config/routes.rb
Rails.application.routes.draw do

  resources :tags, only: [:show]
  resources :votes
  resources :subfreds
  resources :users
  root 'posts#index'
  resources :posts do
    resources :comments
    member do
    get :vote
    get :link_vote
    get :down_vote
  end
end
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create', as: :login_user
  get '/logout' => 'sessions#destroy', as: :logout
  get '/signup' => 'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :subfred
  has_many :votes
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  validates_presence_of :title, :link
  validates :link, uniqueness: true


  def tag_names
    tags.collect(&:name).join(", ")
  end

end

app/models/subfred.rb
class Subfred < ApplicationRecord
  has_many :posts
  validates_presence_of :name
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :taggings
  has_many :posts, through: :taggings

  def to_param
    name
  end

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :comments
  has_many :posts
  has_many :votes
  validates_presence_of :name, :email
  validates :name, :email, uniqueness: true
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    @comment.user = current_user
    if @comment.save
      flash[:success] = "You have successfully farted into the wind!"
      redirect_to @post
    else
      flash[:danger] = "Something went wrong! :("
      redirect_to :back
    end
  end

  def show
    @comment = Comment.find(params[:id])
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only: [:vote, :link_vote, :down_vote]
  # before_action :require_logged_in, except: [:index, :link_vote]

  def index
    @posts = Post.order(vote_count: :DESC)
  end

  def show
    @post = Post.find(params[:id])
  end


  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.vote_count = @post.votes.count
    if current_user.posts << @post
      tags = params[:post][:tag_names].split(",").collect(&:strip)
      tags.each do |tag|
        @post.tags << Tag.find_or_initialize_by(name: tag)
      end
      @post.votes << Vote.create!(user_id: @post.user_id, post_id: @post.id)
      @post.vote_count = @post.votes.count
      @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def vote
    if current_user
      @post.votes << Vote.create!(user_id: @post.user_id, post_id: @post.id)
      @post.vote_count = @post.votes.count
      @post.save
      redirect_to :root
    else
      flash[:warning] = "You must be logged in to vote!"
      redirect_to :login
    end
  end

  def link_vote
    @post.votes << Vote.create!(user_id: @post.user_id, post_id: @post.id)
    @post.vote_count = @post.votes.count
    @post.save
    redirect_to @post.link
  end

  def down_vote
    if logged_in?
      @post.votes.last.destroy
      @post.vote_count = @post.votes.count
      @post.save
      redirect_to :root
      else
        flash[:warning] = "You must be logged in to down vote!"
        redirect_to :login
    end
  end


  def edit
    render :new
  end

  def update
    @post.update(post_params)
    @post.save
    redirect_to :root
  end

private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :link, :summary, :subfred_id)
  end

  def non_unique_link
    repost = Post.find_by(link: @post.link)
    repost.increment!(:vote)
    redirect_to :root
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    if logged_in?
      flash[:warning] = "You are already logged in!"
      redirect_to :root
    end
  end

  def stuff
  end

  def create
      user = User.find_by(name: params[:session][:name])&.authenticate(params[:session][:password])
      if user
          session[:user_id] = user.id
          redirect_to :root
        else
          flash.now[:warning] = "Your credentials do not match!"
          render :new
      end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have been successfully logged out!"
    redirect_to :root
  end

end

app/controllers/subfreds_controller.rb
class SubfredsController < ApplicationController



  def new
    @subfred = Subfred.new
  end

  def create
    @subfred = Subfred.new(subfred_params)
    @subfred.save
    if @subfred.save
      redirect_to root_path
    else
      render :new
    end
  end



  def edit
    render :new
  end

  def update
    @subfred.update(subfred_params)
    @subfred.save
    redirect_to :root
  end

private

  def find_subfred
    @subfred = subfred.find(params[:id])
  end

  def subfred_params
    params.require(:subfred).permit(:name)
  end


end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tags = Tag.find_by(name: params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    # before_action :find_user, only: [:edit, :update]


    def new
      if logged_out?
        @user = User.new
      else
        flash[:warning] = "You already have an account!"
        redirect_to :root
      end
    end

    def create
      @user = User.new(user_params)
      @user.save
      if @user.save
        redirect_to root_path
      else
        render :new
      end
    end


  private

    def user_params
      params.require(:user).permit(:name, :email, :bio, :password, :password_confirmation)
    end


end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subfreds_helper.rb
module SubfredsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/show.html.erb
<h4><%= simple_format(@comment.body) %></h4>
<h5>Submitted by: <%= @comment.user.name %> at <%=(@comment.created_at).in_time_zone('Eastern Time (US & Canada)').strftime("%v %R")%> EST</h5>

app/views/posts/index.html.erb
<table class="table table-striped">
    <% @posts.each do |post| %>
    <tr>
    <td>
        <%= post.vote_count %>
    </td>
    <% if current_user %>
    <td>
        <div class="vote">
            <%= link_to "+1", vote_post_path(post), class: "btn btn-warning btn-xs vote" %>
        </div>
        <div class="vote">
            <%= link_to "-1", down_vote_post_path(post), class: "btn btn-info btn-xs vote" %>
        </div>
    </td>
    <% end %>
    <td>
        <div class="post-column">
            <%=  link_to post.title, link_vote_post_path(post) %>
            <%= post.summary %>
            <%= link_to "Comments", post %>

        </div>
        <div class="post-column">
            SubFred: <%= post.subfred.name %>
            Submitted at: <%= (post.created_at).in_time_zone('Eastern Time (US & Canada)').strftime("%v %R") %> EST
            Tags: <% post.tags.each do |tag| %>
                <%= link_to tag.name, tag, class: "btn btn-info" %>
                <% end %>
        </div>


    </td>
    <td>
        Submitted by: <%= post.user.name %>
    </td>
    </tr>

    <% end %>
</table>

app/views/posts/new.html.erb
<%= simple_form_for(@post, html: { class: 'form-horizontal' }) do |f| %>
<%= f.input :title %>
<%= f.input :link  %>
<%= f.input :summary %>
<%= f.input :tag_names, hint: "Please seperate the tags with commas!" %>
<%= f.association :subfred %>


<%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<h6> Submitted by: <%=@post.user.name %> at <%= (@post.created_at).in_time_zone('Eastern Time (US & Canada)').strftime("%v %R")%> EST</h6>
<h4><%= @post.summary %></h4>

<h3>Comments</h3>
  <% if current_user %>
    <%= simple_form_for [@post, Comment.new] do |f| %>
      <%= f.input :body %>
      <%= f.submit "Fart Away!!", class: "btn btn-primary" %>
    <% end %>
  <% end %>

<% @post.comments.each do |comment| %>
<table class="table table-bordered">
  <tr>
    <td>
      <div class="col-md-9">
          <p><%= simple_format(comment.body)%></p>
      </div>
      <div class="col-md-3">
        <h5>Submitted by: <%= comment.user.name %></h5>
        <h5><%=(comment.created_at).in_time_zone('Eastern Time (US & Canada)').strftime("%v %R")%> EST</h5>
        <h6><%= link_to "View comment", post_comment_path(comment.post, comment) %></h6>
      </div>

    </td>
  </tr>
</table>
<% end %>

app/views/subfreds/new.html.erb
<%= simple_form_for(@subfred) do |f| %>
<%= f.input :name %>

<%= f.button :submit, class: "btn btn-primary" %>
<% end %>

app/views/tags/show.html.erb
<h1><%= @tags.name %></h1>
<table class="table table-striped">
    <% @tags.posts.each do |post| %>
    <tr>
    <td>
        <%= post.vote_count %>
    </td>
    <% if current_user %>
    <td>
        <div class="vote">
            <%= link_to "+1", vote_post_path(post), class: "btn btn-warning btn-xs vote" %>
        </div>
        <div class="vote">
            <%= link_to "-1", down_vote_post_path(post), class: "btn btn-info btn-xs vote" %>
        </div>
    </td>
    <% end %>
    <td>
        <div class="post-column">
            <%=  link_to post.title, link_vote_post_path(post) %>
            <%= post.summary %>
            <%= link_to "Comments", post %>

        </div>
        <div class="post-column">
            SubFred: <%= post.subfred.name %>
            Submitted at: <%= (post.created_at).in_time_zone('Eastern Time (US & Canada)').strftime("%v %R") %> EST
            Tags: <% post.tags.each do |tag| %>
                <%= link_to tag.name, tag, class: "btn btn-info"%>
                <% end %>
        </div>


    </td>
    <td>
        Submitted by: <%= post.user.name %>
    </td>
    </tr>

    <% end %>
</table>

app/views/users/new.html.erb
<%= simple_form_for(@user) do |f| %>
<%= f.input :name %>
<%= f.input :email %>
<%= f.input :bio %>
<%= f.input :password %>
<%= f.input :password_confirmation %>

<%= f.button :submit, class: "btn btn-primary" %>
<% end %>