config/routes.rb
Rails.application.routes.draw do

  resources :tags, only: [:show]
  resources :votes
  resources :subfreds
  resources :users
  root 'posts#index'
  resources :posts do
    resources :comments
    member do
    get :vote
    get :link_vote
    get :down_vote
  end
end
  get '/login' => 'sessions#new', as: :login
  post '/login' => 'sessions#create', as: :login_user
  get '/logout' => 'sessions#destroy', as: :logout
  get '/signup' => 'users#new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  belongs_to :subfred
  has_many :votes
  has_many :comments
  has_many :taggings
  has_many :tags, through: :taggings
  validates_presence_of :title, :link
  validates :link, uniqueness: true


  def tag_names
    tags.collect(&:name).join(", ")
  end

end

app/models/subfred.rb
class Subfred < ApplicationRecord
  has_many :posts
  validates_presence_of :name
end

app/models/tag.rb
class Tag < ApplicationRecord

  has_many :taggings
  has_many :posts, through: :taggings

  def to_param
    name
  end

end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :post
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :comments
  has_many :posts
  has_many :votes
  validates_presence_of :name, :email
  validates :name, :email, uniqueness: true
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :find_post, only: [:vote, :link_vote, :down_vote]
  # before_action :require_logged_in, except: [:index, :link_vote]

  def index
    @posts = Post.order(vote_count: :DESC)
  end

  def show
    @post = Post.find(params[:id])
  end


  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    @post.vote_count = @post.votes.count
    if current_user.posts << @post
      tags = params[:post][:tag_names].split(",").collect(&:strip)
      tags.each do |tag|
        @post.tags << Tag.find_or_initialize_by(name: tag)
      end
      @post.votes << Vote.create!(user_id: @post.user_id, post_id: @post.id)
      @post.vote_count = @post.votes.count
      @post.save
      redirect_to root_path
    else
      render :new
    end
  end

  def vote
    if current_user
      @post.votes << Vote.create!(user_id: @post.user_id, post_id: @post.id)
      @post.vote_count = @post.votes.count
      @post.save
      redirect_to :root
    else
      flash[:warning] = "You must be logged in to vote!"
      redirect_to :login
    end
  end

  def link_vote
    @post.votes << Vote.create!(user_id: @post.user_id, post_id: @post.id)
    @post.vote_count = @post.votes.count
    @post.save
    redirect_to @post.link
  end

  def down_vote
    if logged_in?
      @post.votes.last.destroy
      @post.vote_count = @post.votes.count
      @post.save
      redirect_to :root
      else
        flash[:warning] = "You must be logged in to down vote!"
        redirect_to :login
    end
  end


  def edit
    render :new
  end

  def update
    @post.update(post_params)
    @post.save
    redirect_to :root
  end

private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :link, :summary, :subfred_id)
  end

  def non_unique_link
    repost = Post.find_by(link: @post.link)
    repost.increment!(:vote)
    redirect_to :root
  end

end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def show
    @tags = Tag.find_by(name: params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController


    # before_action :find_user, only: [:edit, :update]


    def new
      if logged_out?
        @user = User.new
      else
        flash[:warning] = "You already have an account!"
        redirect_to :root
      end
    end

    def create
      @user = User.new(user_params)
      @user.save
      if @user.save
        redirect_to root_path
      else
        render :new
      end
    end


  private

    def user_params
      params.require(:user).permit(:name, :email, :bio, :password, :password_confirmation)
    end


end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/subfreds_helper.rb
module SubfredsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freddit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <h2><%= link_to "FREDdit", root_path %> </h2>
      <% if current_user %>
        <div class="col-md-3">
          <%= link_to "Create new post!", new_post_path, class:"btn btn-success" %>
        </div>
        <div class="col-md-3 col-md-offset-6">
          <%= current_user.name %>
          <%= link_to "Log Out!", logout_path, class:"btn btn-danger" %>
        </div>
        <div class="col-md-3 col-md-offset-9">
            <%= link_to "New Subfred!", new_subfred_path, class: "btn btn-success" %>
        </div>
        <% else %>
      <div class="col-md-3">
          <%= link_to "New User!", new_user_path, class: "btn btn-success" %>
      </div>
      <div class="col-md-3 col-md-offset-6">
        <%= link_to "Login!", login_path, class: "btn btn-success" %>
      </div>
      <% end %>
      <% if flash.any? %>
        <% flash.each do |key, message| %>
          <div class="alert alert-<%= key %> row" role="alert">
            <p>
              <%= message %>
            </p>
          </div>
        <% end %>
      <% end %>

      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>